---
# Configure ansible
- hosts: localhost
  become_method: sudo
  become: true
  tasks:
  - name: copy ansible hosts
    copy: src="src/hosts" dest="/etc/ansible/hosts" owner=root group=root mode=0644
  - name: copy ansible Configure
    copy: src="src/ansible.cfg" dest="/etc/ansible/ansible.cfg" owner=root group=root mode=0644
